
---
include:
  - board: nice_nano_v2
    shield: Lily58_dongle_left nice_oled
    artifact-name: Lily58_peripheral_left_oled
  - board: nice_nano_v2
    shield: Lily58_dongle_right nice_oled
    artifact-name: Lily58_peripheral_right_oled   
  - board: seeeduino_xiao_ble
    shield: Lily58_dongle_central
    snippet: studio-rpc-usb-uart
    artifact-name: Lily58_central_dongle
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
